// packages/lux/src/components/lux-text/lux-text.tsx
import { Component, Prop, Element, h } from '@stencil/core';
import { getConfig } from '../../utils/config-scope';
import { density } from '../../design-tokens';

/**
 * @component lux-text
 * @experimental
 * 
 * A text component that displays text content with automatic density adaptation.
 * 
 * @example
 * ```html
 * <lux-text>Regular text</lux-text>
 * <lux-text size="lg" weight="bold">Large bold text</lux-text>
 * ```
 * 
 * @slot - Text content
 */
@Component({
  tag: 'lux-text',
  styleUrl: 'lux-text.scss',
  shadow: true,
})
export class LuxText {
  /**
   * Text size
   * @experimental
   */
  @Prop() size?: 'xs' | 'sm' | 'base' | 'lg' | 'xl';

  /**
   * Font weight
   * @experimental
   */
  @Prop() weight?: 'normal' | 'medium' | 'semibold' | 'bold';

  /**
   * Text color variant
   * @experimental
   */
  @Prop() color?: 'default' | 'muted' | 'primary' | 'error' | 'success';

  @Element() el!: HTMLElement;

  private config = { density: 'comfortable' as const };

  componentWillLoad() {
    this.updateConfig();
  }

  componentWillUpdate() {
    this.updateConfig();
  }

  private updateConfig() {
    this.config = getConfig(this.el);
  }

  render() {
    const densityConfig = density[this.config.density];
    const fontSize = this.size 
      ? `var(--lux-font-size-${this.size})` 
      : densityConfig.fontSize;
    
    return (
      <span
        class={{
          'lux-text': true,
          [`lux-text--${this.size || 'base'}`]: true,
          [`lux-text--${this.weight || 'normal'}`]: true,
          [`lux-text--${this.color || 'default'}`]: true,
        }}
        style={{
          '--lux-text-font-size': fontSize,
        }}
      >
        <slot />
      </span>
    );
  }
}

// packages/lux-angular/src/components/lux-text/lux-text.component.ts
/**
 * @fileoverview Angular component wrapper for lux-text
 * @experimental
 */

import { Component, Input } from '@angular/core';

/**
 * @experimental
 */
@Component({
  selector: 'lux-text',
  template:
    '<lux-text [size]="size" [weight]="weight" [color]="color"><ng-content></ng-content></lux-text>',
  styles: [':host { display: inline; }'],
})
export class LuxTextComponent {
  @Input() size?: 'xs' | 'sm' | 'base' | 'lg' | 'xl';
  @Input() weight?: 'normal' | 'medium' | 'semibold' | 'bold';
  @Input() color?: 'default' | 'muted' | 'primary' | 'error' | 'success';
}
