// packages/lux-react/src/components/lux-tabs.tsx
/**
 * @fileoverview React wrappers for lux-tabs
 * @experimental
 */

import React from 'react';

export interface LuxTabsProps extends React.HTMLAttributes<HTMLLuxTabsElement> {
  activeIndex?: number;
}

export interface LuxTabProps extends React.HTMLAttributes<HTMLLuxTabElement> {
  label: string;
}

/**
 * @experimental
 */
export const LuxTabs = React.forwardRef<HTMLLuxTabsElement, LuxTabsProps>(
  ({ children, ...props }, ref) => {
    return React.createElement('lux-tabs', { ...props, ref }, children);
  }
);

LuxTabs.displayName = 'LuxTabs';

/**
 * @experimental
 */
export const LuxTab = React.forwardRef<HTMLLuxTabElement, LuxTabProps>(
  ({ children, ...props }, ref) => {
    return React.createElement('lux-tab', { ...props, ref }, children);
  }
);

LuxTab.displayName = 'LuxTab';

// packages/lux-angular/src/components/lux-tabs/lux-tabs.component.ts
/**
 * @fileoverview Angular component wrappers for lux-tabs
 * @experimental
 */

import { Component, Input } from '@angular/core';

/**
 * @experimental
 */
@Component({
  selector: 'lux-tabs',
  template: '<lux-tabs [activeIndex]="activeIndex"><ng-content></ng-content></lux-tabs>',
  styles: [':host { display: block; }'],
})
export class LuxTabsComponent {
  @Input() activeIndex = 0;
}

/**
 * @experimental
 */
@Component({
  selector: 'lux-tab',
  template: '<lux-tab [label]="label"><ng-content></ng-content></lux-tab>',
  styles: [':host { display: block; }'],
})
export class LuxTabComponent {
  @Input() label!: string;
}
