// packages/lux-angular/src/components/lux-data-table/lux-data-table.component.ts
/**
 * @fileoverview Angular component wrapper for lux-data-table
 * @experimental
 */

import { Component, Input } from '@angular/core';

/**
 * @experimental
 */
@Component({
  selector: 'lux-data-table',
  template: '<lux-data-table [columnDefs]="columnDefs" [rowData]="rowData" [gridOptions]="gridOptions"></lux-data-table>',
  styles: [':host { display: block; }'],
})
export class LuxDataTableComponent {
  @Input() columnDefs?: string;
  @Input() rowData?: string;
  @Input() gridOptions?: string;
}

// packages/lux-react/src/components/lux-data-table.tsx
/**
 * @fileoverview React wrapper for lux-data-table
 * @experimental
 */

import React from 'react';

export interface LuxDataTableProps extends React.HTMLAttributes<HTMLLuxDataTableElement> {
  columnDefs?: string;
  rowData?: string;
  gridOptions?: string;
}

/**
 * @experimental
 */
export const LuxDataTable = React.forwardRef<HTMLLuxDataTableElement, LuxDataTableProps>(
  ({ ...props }, ref) => {
    return React.createElement('lux-data-table', { ...props, ref });
  }
);

LuxDataTable.displayName = 'LuxDataTable';
