// packages/lux-angular/src/components/lux-text/lux-text.component.ts
/**
 * @fileoverview Angular component wrapper for lux-text
 * @experimental
 */

import { Component, Input } from '@angular/core';

/**
 * @experimental
 */
@Component({
  selector: 'lux-text',
  template:
    '<lux-text [size]="size" [weight]="weight" [color]="color"><ng-content></ng-content></lux-text>',
  styles: [':host { display: inline; }'],
})
export class LuxTextComponent {
  @Input() size?: 'xs' | 'sm' | 'base' | 'lg' | 'xl';
  @Input() weight?: 'normal' | 'medium' | 'semibold' | 'bold';
  @Input() color?: 'default' | 'muted' | 'primary' | 'error' | 'success';
}

// packages/lux-react/src/components/lux-text.tsx
/**
 * @fileoverview React wrapper for lux-text
 * @experimental
 */

import React from 'react';

export interface LuxTextProps extends React.HTMLAttributes<HTMLLuxTextElement> {
  size?: 'xs' | 'sm' | 'base' | 'lg' | 'xl';
  weight?: 'normal' | 'medium' | 'semibold' | 'bold';
  color?: 'default' | 'muted' | 'primary' | 'error' | 'success';
}

/**
 * @experimental
 */
export const LuxText = React.forwardRef<HTMLLuxTextElement, LuxTextProps>(
  ({ children, ...props }, ref) => {
    return React.createElement('lux-text', { ...props, ref }, children);
  }
);

LuxText.displayName = 'LuxText';
