// packages/lux-angular/src/components/lux-card/lux-card.component.ts
/**
 * @fileoverview Angular component wrapper for lux-card
 * @experimental
 */

import { Component, Input } from '@angular/core';

/**
 * @experimental
 */
@Component({
  selector: 'lux-card',
  template: `
    <lux-card [variant]="variant">
      <div slot="header"><ng-content select="[slot=header]"></ng-content></div>
      <ng-content></ng-content>
      <div slot="footer"><ng-content select="[slot=footer]"></ng-content></div>
    </lux-card>
  `,
  styles: [':host { display: block; }'],
})
export class LuxCardComponent {
  @Input() variant?: 'default' | 'outlined' | 'elevated';
}

// packages/lux-react/src/components/lux-card.tsx
/**
 * @fileoverview React wrapper for lux-card
 * @experimental
 */

import React from 'react';

export interface LuxCardProps extends React.HTMLAttributes<HTMLLuxCardElement> {
  variant?: 'default' | 'outlined' | 'elevated';
}

/**
 * @experimental
 */
export const LuxCard = React.forwardRef<HTMLLuxCardElement, LuxCardProps>(
  ({ children, ...props }, ref) => {
    return React.createElement('lux-card', { ...props, ref }, children);
  }
);

LuxCard.displayName = 'LuxCard';
