// packages/lux-angular/src/components/lux-heading/lux-heading.component.ts
/**
 * @fileoverview Angular component wrapper for lux-heading
 * @experimental
 */

import { Component, Input } from '@angular/core';

/**
 * @experimental
 */
@Component({
  selector: 'lux-heading',
  template: '<lux-heading [level]="level"><ng-content></ng-content></lux-heading>',
  styles: [':host { display: block; }'],
})
export class LuxHeadingComponent {
  @Input() level: 1 | 2 | 3 | 4 | 5 | 6 = 1;
}

// packages/lux-react/src/components/lux-heading.tsx
/**
 * @fileoverview React wrapper for lux-heading
 * @experimental
 */

import React from 'react';

export interface LuxHeadingProps extends React.HTMLAttributes<HTMLLuxHeadingElement> {
  level?: 1 | 2 | 3 | 4 | 5 | 6;
}

/**
 * @experimental
 */
export const LuxHeading = React.forwardRef<HTMLLuxHeadingElement, LuxHeadingProps>(
  ({ children, ...props }, ref) => {
    return React.createElement('lux-heading', { ...props, ref }, children);
  }
);

LuxHeading.displayName = 'LuxHeading';
