// packages/lux-react/src/components/lux-scope.tsx
/**
 * @fileoverview React wrapper for lux-scope
 * @experimental
 */

import React from 'react';

export interface LuxScopeProps extends React.HTMLAttributes<HTMLLuxScopeElement> {
  density?: 'compact' | 'comfortable' | 'spacious';
  mainColor?: string;
}

/**
 * @experimental
 */
export const LuxScope = React.forwardRef<HTMLLuxScopeElement, LuxScopeProps>(
  ({ children, ...props }, ref) => {
    return React.createElement('lux-scope', { ...props, ref }, children);
  }
);

LuxScope.displayName = 'LuxScope';

// packages/lux-angular/src/components/lux-scope/lux-scope.component.ts
/**
 * @fileoverview Angular component wrapper for lux-scope
 * @experimental
 */

import { Component, Input } from '@angular/core';

/**
 * @experimental
 */
@Component({
  selector: 'lux-scope',
  template:
    '<lux-scope [density]="density" [mainColor]="mainColor"><ng-content></ng-content></lux-scope>',
  styles: [':host { display: contents; }'],
})
export class LuxScopeComponent {
  @Input() density?: 'compact' | 'comfortable' | 'spacious';
  @Input() mainColor?: string;
}
