// packages/lux-react/src/components/lux-button.tsx
/**
 * @fileoverview React wrapper for lux-button
 * @experimental
 */

import React from 'react';

export interface LuxButtonProps extends React.HTMLAttributes<HTMLLuxButtonElement> {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost';
  disabled?: boolean;
  type?: 'button' | 'submit' | 'reset';
  onClick?: (event: CustomEvent<MouseEvent>) => void;
}

/**
 * @experimental
 */
export const LuxButton = React.forwardRef<HTMLLuxButtonElement, LuxButtonProps>(
  ({ children, ...props }, ref) => {
    return React.createElement('lux-button', { ...props, ref }, children);
  }
);

LuxButton.displayName = 'LuxButton';

// packages/lux-angular/src/components/lux-button/lux-button.component.ts
/**
 * @fileoverview Angular component wrapper for lux-button
 * @experimental
 */

import { Component, Input, Output, EventEmitter, ElementRef } from '@angular/core';

/**
 * @experimental
 */
@Component({
  selector: 'lux-button',
  template: '<lux-button [variant]="variant" [disabled]="disabled" [type]="type" (luxClick)="onClick.emit($event)"><ng-content></ng-content></lux-button>',
  styles: [':host { display: inline-block; }'],
})
export class LuxButtonComponent {
  @Input() variant?: 'primary' | 'secondary' | 'outline' | 'ghost' = 'primary';
  @Input() disabled = false;
  @Input() type: 'button' | 'submit' | 'reset' = 'button';
  @Output() onClick = new EventEmitter<CustomEvent<MouseEvent>>();

  constructor(private elementRef: ElementRef) {}
}
